[package]
name = "TokenObjects"
version = "0.0.0"

[addresses]
token_objects = "_"

[dependencies]
DiemFramework = { local = "../../../framework/diem-framework" }
DiemTokenObjects = { local = "../../../framework/diem-token-objects" }
