[tool.poetry]
name = "diem-cli-e2e-tests"
version = "0.1.0"
description = "Diem CLI E2E tests"
authors = ["Diem Labs <opensource@diemlabs.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.7 <3.10"
diem-sdk = "^0.5.1"
requests = "^2.31.0"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
