[package]
name = "diem-indexer-grpc-integration-tests"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
diem-config = { workspace = true }
diem-indexer-grpc-cache-worker = { workspace = true }
diem-indexer-grpc-data-service = { workspace = true }
diem-indexer-grpc-file-store = { workspace = true }
diem-indexer-grpc-server-framework = { workspace = true }
diem-indexer-grpc-utils = { workspace = true }
diem-inspection-service = { workspace = true }
diem-logger = { workspace = true }
diem-protos = { workspace = true }
diem-runtimes = { workspace = true }
diem-transaction-emitter-lib = { workspace = true }
diem-transaction-generator-lib = { workspace = true }
diem-types = { workspace = true }
async-trait = { workspace = true }
backoff = { workspace = true }
base64  = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
futures-core = { workspace = true }
futures-util = { workspace = true }
itertools = { workspace = true }
prometheus = { workspace = true }
prost = { workspace = true }
redis = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
warp = { workspace = true }

[features]
integration-tests = []
