[package]
name = "cli_e2e_tests"
version = "0.0.1"

[addresses]
addr = "_"

[dev-addresses]
addr = "0x12345"

[dependencies.DiemFramework]
git = "https://github.com/aptos-labs/diem-core.git"
rev = "devnet"
subdir = "diem-move/framework/diem-framework"

[dependencies.DiemTokenObjects]
git = "https://github.com/aptos-labs/diem-core.git"
rev = "devnet"
subdir = "diem-move/framework/diem-token-objects"
