[package]
name = "diem-data-streaming-service"
description = "The data streaming service that sends data notifications to clients"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
diem-channels = { workspace = true }
diem-config = { workspace = true }
diem-crypto = { workspace = true }
diem-data-client = { workspace = true }
diem-id-generator = { workspace = true }
diem-infallible = { workspace = true }
diem-logger = { workspace = true }
diem-metrics-core = { workspace = true }
diem-network = { workspace = true }
diem-short-hex-str = { workspace = true }
diem-types = { workspace = true }
async-trait = { workspace = true }
enum_dispatch = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }

[dev-dependencies]
diem-storage-service-types = { workspace = true }
diem-types = { workspace = true, features = ["fuzzing"] }
claims = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
