[package]
name = "diem-storage-service-server"
description = "The Diem storage service (server-side)"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
diem-bounded-executor = { workspace = true }
diem-channels = { workspace = true }
diem-config = { workspace = true }
diem-infallible = { workspace = true }
diem-logger = { workspace = true }
diem-metrics-core = { workspace = true }
diem-network = { workspace = true }
diem-storage-interface = { workspace = true }
diem-storage-service-types = { workspace = true }
diem-time-service = { workspace = true }
diem-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
lru = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
diem-bitvec = { workspace = true }
diem-config = { workspace = true, features = ["fuzzing"] }
diem-crypto = { workspace = true }
diem-netcore = { workspace = true }
diem-storage-interface = { workspace = true }
diem-time-service = { workspace = true, features = ["async", "testing"] }
diem-types = { workspace = true }
claims = { workspace = true }
maplit = { workspace = true }
mockall = { workspace = true }
rand = { workspace = true }
