[package]
name = "Examples"
version = "0.0.0"

[dependencies]
DiemFramework = { local = "../../../framework/diem-framework" }
DiemToken = { local = "../../../framework/diem-token" }

[addresses]
diem_framework = "0x1"
# replace the admin_addr with the actual admin address we created using CLI
admin_addr = "0xbeef"