[package]
name = "ApiTest"
version = "0.0.0"

[addresses]
# test user address to be installed dynamically on build

[dependencies]
DiemFramework = { local = "../../diem-move/framework/diem-framework" }
