[package]
name = "e2e-move-tests"
description = "Move e2e tests"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
diem = { workspace = true }
diem-block-executor = { workspace = true }
diem-cached-packages = { workspace = true }
diem-crypto = { workspace = true }
diem-framework = { workspace = true }
diem-gas = { workspace = true, features = ["testing"] }
diem-gas-profiling = { workspace = true }
diem-keygen = { workspace = true }
diem-language-e2e-tests = { workspace = true }
diem-logger = { workspace = true }
diem-package-builder = { workspace = true }
diem-state-view = { workspace = true }
diem-types = { workspace = true }
diem-vm = { workspace = true }
diem-vm-genesis = { workspace = true }
diem-writeset-generator = { workspace = true }
bcs = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-package = { workspace = true }
move-symbol-pool = { workspace = true }
once_cell = { workspace = true }
project-root = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }
rstest = { workspace = true }
serde = { workspace = true }
tempfile = { workspace = true }

[lib]
doctest = false
