[package]
name = "basic_coin"
version = "0.0.0"

[addresses]
named_addr = "0xCAFE"

[dependencies.DiemStdlib]
git = 'https://github.com/aptos-labs/diem-core.git'
rev = 'main'
subdir = 'diem-move/framework/diem-stdlib'
