{{ $fullnode_statefulset := lookup "apps/v1" "StatefulSet" $.Release.Namespace (include "diem-fullnode.fullname" .) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "diem-fullnode.fullname" . }}
  labels:
    {{- include "diem-fullnode.labels" . | nindent 4 }}
    app.kubernetes.io/name: fullnode
spec:
  serviceName: {{ include "diem-fullnode.fullname" . }}
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "diem-fullnode.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: fullnode
  template:
    metadata:
      labels:
        {{- include "diem-fullnode.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: fullnode
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: fullnode
        {{- if and $fullnode_statefulset (not $.Values.manageImages) }} # if the statefulset already exists and we do not want helm to simply overwrite the image, use the existing image
        image: {{ (first $fullnode_statefulset.spec.template.spec.containers).image }}
        {{- else }}
        image: {{ .Values.image.repo }}:{{ .Values.image.tag | default $.Values.imageTag }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /bin/sh
        - -c
        - |-
          set -e
          {{- if and (not .Values.chain.genesisConfigmap) (not .Values.chain.genesisSecret) }}
          # Download genesis and waypoint if necessary
          curl -o /opt/diem/genesis/waypoint.txt {{ (get .Values.diem_chains .Values.chain.name).waypoint_txt_url }}
          curl -o /opt/diem/genesis/genesis.blob {{ (get .Values.diem_chains .Values.chain.name).genesis_blob_url }}
          {{- end }}
          # Start the node
          /usr/local/bin/diem-node -f /opt/diem/etc/fullnode.yaml
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: RUST_LOG
          value: {{ .Values.rust_log }}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RUST_BACKTRACE
          value: "0"
        volumeMounts:
        - name: diem-config
          mountPath: /opt/diem/etc
        - name: diem-genesis
          mountPath: /opt/diem/genesis
        - name: diem-data
          mountPath: /opt/diem/data
        - name: tmp
          mountPath: /tmp
        ports:
        - containerPort: 6182
        - containerPort: 6186
        - containerPort: 8081
        - containerPort: 8080
          name: api
        - containerPort: 9101
          name: metrics
        # NOTE: these require the API to be enabled, which is not always the case
        livenessProbe: # restart the pod if the REST API is ever unresponsive
          httpGet:
            path: /v1/-/healthy
            port: 8080
          initialDelaySeconds: 30
        readinessProbe: # pod is ready when state sync is caught up
          httpGet:
            path: /v1/-/healthy?duration_secs=10
            port: 8080
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 6180
        runAsGroup: 6180
        fsGroup: 6180
      volumes:
      - name: diem-config
        configMap:
          name: {{ include "diem-fullnode.fullname" . }}
      - name: diem-genesis
      {{- if .Values.chain.genesisConfigmap }}
        configMap:
          name: {{ .Values.chain.genesisConfigmap }}
      {{- else if .Values.chain.genesisSecret }}
        secret:
          secretName: {{ .Values.chain.genesisSecret }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: diem-data
        persistentVolumeClaim:
          claimName: {{ include "diem-fullnode.fullname" . }}-e{{ .Values.chain.era }}
      - name: tmp
        emptyDir: {}
      serviceAccountName: {{ include "diem-fullnode.serviceAccountName" . }}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{.Values.imagePullSecret}}
      {{- end }}
