[package]
name = 'my_todo_list'
version = '1.0.0'
[dependencies.DiemFramework]
git = 'https://github.com/aptos-labs/diem-core.git'
rev = 'main'
subdir = 'diem-move/framework/diem-framework'
[addresses]
todolist_addr='_'