name: "Get latest Diem CLI"
description: |
  Fetches the latest released Diem CLI.
inputs:
  destination_directory:
    description: "Directory to install the CLI in"
    required: true

runs:
  using: composite
  steps:
    - name: Setup python
      uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # pin@v4
    - name: Get installation script
      shell: bash
      run: |
        curl -fsSL "https://diem.dev/scripts/install_cli.py" > install_cli.py
    - name: Run installation script
      shell: bash
      run: |
        python3 install_cli.py --bin-dir ${{ inputs.destination_directory }}
