[package]
name = "diem-debugger"
version = "0.1.0"
authors = ["Diem Labs <opensource@diemlabs.com>"]
description = "A tool to replay transactions on chain and to execute transactions locally with remote backend"
repository = "https://github.com/aptos-labs/diem-core"
homepage = "https://diemlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { workspace = true }
diem-crypto = { workspace = true }
diem-gas = { workspace = true }
diem-gas-profiling = { workspace = true }
diem-logger = { workspace = true }
diem-resource-viewer = { workspace = true }
diem-rest-client = { workspace = true }
diem-state-view = { workspace = true }
diem-types = { workspace = true }
diem-validator-interface = { workspace = true }
diem-vm = { workspace = true }
diem-vm-logging = { workspace = true }
diem-vm-types = { workspace = true }
clap = { workspace = true }
move-binary-format = { workspace = true }
move-cli = { workspace = true }
move-compiler = { workspace = true }
move-core-types = { workspace = true }
move-resource-viewer = { workspace = true }
move-table-extension = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-test-utils = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
