[package]
name = "diem-executor-benchmark"
description = "Diem executor benchmark"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
diem-block-executor = { workspace = true }
diem-block-partitioner = { workspace = true }
diem-config = { workspace = true }
diem-crypto = { workspace = true }
diem-db = { workspace = true }
diem-executor = { workspace = true }
diem-executor-types = { workspace = true }
diem-genesis = { workspace = true, features = ["testing"] }
diem-infallible = { workspace = true }
diem-jellyfish-merkle = { workspace = true }
diem-logger = { workspace = true }
diem-metrics-core = { workspace = true }
diem-push-metrics =  { workspace = true }
diem-schemadb = { workspace = true }
diem-scratchpad = { workspace = true }
diem-sdk = { workspace = true }
diem-state-view = { workspace = true }
diem-storage-interface = { workspace = true }
diem-transaction-generator-lib = { workspace = true }
diem-types = { workspace = true }
diem-vm = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
criterion = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
move-core-types = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }

[target.'cfg(unix)'.dependencies]
jemallocator = { workspace = true }

[dev-dependencies]
diem-temppath = { workspace = true }

[features]
default = []
fuzzing = ["diem-config/fuzzing", "diem-crypto/fuzzing", "diem-types/fuzzing"]
