[package]
name = "diem-testcases"
description = "Diem compatibility tests"
version = "0.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
diem = { workspace = true, features = ["fuzzing"] }
diem-forge = { workspace = true }
diem-genesis = { workspace = true }
diem-global-constants = { workspace = true }
diem-keygen = { workspace = true }
diem-logger = { workspace = true }
diem-move-examples = { workspace = true }
diem-release-builder = { workspace = true }
diem-rest-client = { workspace = true }
diem-runtimes = { workspace = true }
diem-sdk = { workspace = true }
diem-temppath = { workspace = true }
diem-types = { workspace = true }
bcs = { workspace = true }
csv = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[[test]]
name = "forge-local-compatibility"
harness = false

[[test]]
name = "forge-local-performance"
harness = false
