[package]
name = "ResourceGroupsSecondary"
version = "0.0.0"

[addresses]
resource_groups_primary = "_"
resource_groups_secondary = "_"

[dependencies]
DiemFramework = { local = "../../../framework/diem-framework" }
ResourceGroupsPrimary = { local = "../primary" }
