[package]
name = "diem-network-builder"
description = "Diem network builder for constructing a network"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
diem-channels = { workspace = true }
diem-config = { workspace = true }
diem-crypto = { workspace = true }
diem-event-notifications = { workspace = true }
diem-infallible = { workspace = true }
diem-logger = { workspace = true }
diem-netcore = { workspace = true }
diem-network = { workspace = true }
diem-network-discovery = { workspace = true }
diem-secure-storage = { workspace = true }
diem-time-service = { workspace = true }
diem-types = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
futures = { workspace = true }
maplit = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
