apiVersion: v2
name: diem-genesis
version: 0.1.0
appVersion: 0.1.0
description: Diem blockchain automated genesis ceremony for testnets
home: https://diemlabs.com/
sources:
- https://github.com/aptos-labs/diem-core
