[package]
name = "smoke-test"
description = "Diem end to end tests"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
diem = { workspace = true, features = ["fuzzing"] }
diem-bitvec = { path = "../../crates/diem-bitvec" }
diem-cached-packages = { workspace = true }
diem-config = { workspace = true }
diem-consensus = { workspace = true }
diem-crypto = { workspace = true }
diem-debugger = { workspace = true }
diem-faucet-core = { workspace = true }
diem-forge = { workspace = true }
diem-framework = { workspace = true }
diem-gas = { workspace = true, features = ["testing"] }
diem-global-constants = { workspace = true }
diem-indexer = { workspace = true }
diem-keygen = { workspace = true }
diem-release-builder = { workspace = true }
diem-rest-client = { workspace = true }
diem-rosetta = { workspace = true }
diem-sdk = { workspace = true }
diem-temppath = { workspace = true }
diem-types = { workspace = true }
diem-vm = { workspace = true }
diem-vm-genesis = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
diesel = { workspace = true }
hex = { workspace = true }
move-core-types = { workspace = true }
proptest = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
diem-backup-cli = { workspace = true }
diem-genesis = { workspace = true }
diem-infallible = { workspace = true }
diem-logger = { workspace = true }
diem-secure-storage = { workspace = true }
diem-time-service = { workspace = true }
diem-vault-client = { workspace = true }
diem-writeset-generator = { workspace = true }
base64 = { workspace = true }
futures = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
serde_yaml = { workspace = true }
