[package]
name = "ManagedFungibleToken"
version = "0.0.0"

[addresses]
diem_framework = "0x1"
diem_token_objects = "0x4"
example_addr = "_"

[dependencies]
DiemFramework = { local = "../../../framework/diem-framework" }
DiemTokenObjects = { local = "../../../framework/diem-token-objects" }
ManagedFungibleAsset = { local = "../managed_fungible_asset" }
