[package]
name = "diem-indexer-grpc-cache-worker"
description = "Indexer gRPC worker to collect on-chain data from node gRPC and push to cache."
version = "1.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
diem-indexer-grpc-server-framework = { workspace = true }
diem-indexer-grpc-utils = { workspace = true }
diem-metrics-core = { workspace = true }
diem-moving-average = { workspace = true }
diem-protos = { workspace = true }
diem-runtimes = { workspace = true }
async-trait = { workspace = true }
backoff = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
futures-core = { workspace = true }
once_cell = { workspace = true }
prost = { workspace = true }
redis = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
diem-config = { workspace = true }
reqwest = { workspace = true }
tempfile = { workspace = true }

[features]
integration-tests = []
