[package]
name = "PostMint"
version = "0.0.0"

[dependencies]
DiemFramework = { local = "../../framework/diem-framework" }
DiemToken = { local = "../../framework/diem-token" }

[addresses]
diem_framework = "0x1"
post_mint_reveal_nft = "_"
