[package]
name = "ManagedFungibleToken"
version = "0.0.0"

[addresses]
diem_framework = "0x1"
example_addr = "_"

[dependencies]
DiemFramework = { local = "../../../framework/diem-framework" }
ManagedFungibleAsset = { local = "../managed_fungible_asset" }
