[package]
name = "diem-transaction-emitter-lib"
description = "Library for Diem transaction emitter"
version = "0.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
again = { workspace = true }
anyhow = { workspace = true }
diem = { workspace = true }
diem-config = { workspace = true }
diem-crypto = { workspace = true }
diem-framework = { workspace = true }
diem-global-constants = { workspace = true }
diem-infallible = { workspace = true }
diem-logger = { workspace = true }
diem-rest-client = { workspace = true }
diem-sdk = { workspace = true }
diem-transaction-generator-lib = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
move-binary-format = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
