[package]
name = "diem-vm-logging"
description = "Diem VM speculative logging utility"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
diem-crypto = { workspace = true }
diem-logger = { workspace = true }
diem-metrics-core = { workspace = true }
diem-speculative-state-helper = { workspace = true }
diem-state-view = { workspace = true }
diem-types = { workspace = true }
arc-swap = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
