[package]
name = "diem-db"
description = "Diem database"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
diem-accumulator = { workspace = true }
diem-config = { workspace = true }
diem-crypto = { workspace = true }
diem-db-indexer = { workspace = true }
diem-executor-types = { workspace = true }
diem-infallible = { workspace = true }
diem-jellyfish-merkle = { workspace = true }
diem-logger = { workspace = true }
diem-metrics-core = { workspace = true }
diem-proptest-helpers = { workspace = true, optional = true }
diem-rocksdb-options = { workspace = true }
diem-schemadb = { workspace = true }
diem-scratchpad = { workspace = true }
diem-state-view = { workspace = true }
diem-storage-interface = { workspace = true }
diem-temppath = { workspace = true, optional = true }
diem-types = { workspace = true }
diem-vm = { workspace = true }
arc-swap = { workspace = true }
arr_macro = { workspace = true }
bcs = { workspace = true }
byteorder = { workspace = true }
claims = { workspace = true }
clap = { workspace = true, optional = true }
dashmap = { workspace = true }
itertools = { workspace = true }
lru = { workspace = true }
move-core-types = { workspace = true }
move-resource-viewer = { workspace = true }
num-derive = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
owo-colors = { workspace = true, optional = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
rayon = { workspace = true }
serde = { workspace = true }
static_assertions = { workspace = true }
status-line = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
diem-executor-types = { workspace = true }
diem-jellyfish-merkle = { workspace = true, features = ["fuzzing"] }
diem-proptest-helpers = { workspace = true }
diem-schemadb = { workspace = true, features = ["fuzzing"] }
diem-scratchpad = { workspace = true, features = ["fuzzing"] }
diem-temppath = { workspace = true }
diem-types = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "diem-proptest-helpers", "diem-temppath", "diem-crypto/fuzzing", "diem-jellyfish-merkle/fuzzing", "diem-types/fuzzing", "diem-executor-types/fuzzing", "diem-schemadb/fuzzing", "diem-scratchpad/fuzzing"]
consensus-only-perf-test = []
db-debugger = ["diem-temppath", "clap", "owo-colors"]

[[bin]]
name = "db-debugger"
path = "src/db_debugger/main.rs"
required-features = ["db-debugger"]
