[package]
name = "NFTDAO"
version = "0.0.0"
upgrade_policy = "immutable"

[addresses]
dao_platform = "_"
diem_framework = "0x1"

[dependencies]
DiemFramework = { local = "../../../framework/diem-framework" }
DiemToken = { local = "../../../framework/diem-token" }
