[package]
name = "diem-indexer-grpc-data-service"
description = "Diem Indexer gRPC data service to serve the data from cache and file store."
version = "1.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
diem-indexer-grpc-server-framework = { workspace = true }
diem-indexer-grpc-utils = { workspace = true }
diem-metrics-core = { workspace = true }
diem-moving-average = { workspace = true }
diem-protos = { workspace = true }
diem-runtimes = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true }
cloud-storage = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
prost = { workspace = true }
redis = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
