[package]
name = "diem-gas"
description = "Gas metering for the Diem blockchain"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
diem-framework = { workspace = true }
diem-gas-algebra-ext = { workspace = true }
diem-global-constants = { workspace = true }
diem-logger = { workspace = true }
diem-move-stdlib = { workspace = true }
diem-package-builder = { workspace = true }
diem-types = { workspace = true }
diem-vm-types = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-model = { workspace = true }
move-table-extension = { workspace = true }
move-vm-types = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[features]
testing = ["diem-move-stdlib/testing", "diem-global-constants/testing"]

[[bin]]
name = "diem-gas-gen-update-proposal"
path = "src/bin/gen_proposal.rs"
