[package]
name = "diem-indexer-grpc-fullnode"
description = "Diem Indexer GRPC runtime on fullnode."
version = "1.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
fail = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hyper = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }

diem-api = { workspace = true }
diem-api-types = { workspace = true }
diem-bitvec = { workspace = true }
diem-config = { workspace = true }
diem-logger = { workspace = true }
diem-mempool = { workspace = true }
diem-metrics-core = { workspace = true }
diem-moving-average = { workspace = true }
diem-protos = { workspace = true }
diem-runtimes = { workspace = true }
diem-storage-interface = { workspace = true }
diem-types = { workspace = true }
diem-vm = { workspace = true }

move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-package = { workspace = true }

[dev-dependencies]
goldenfile = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }

diem-api-test-context = { workspace = true }
diem-crypto = { workspace = true }
diem-db = { workspace = true }
diem-executor = { workspace = true }
diem-executor-types = { workspace = true }
diem-framework = { workspace = true }
diem-genesis = { workspace = true }
diem-global-constants = { workspace = true }
diem-mempool = { workspace = true }
diem-mempool-notifications = { workspace = true }
diem-proptest-helpers = { workspace = true }
diem-sdk = { workspace = true }
diem-secure-storage = { workspace = true }
diem-temppath = { workspace = true }
diem-vm = { workspace = true }
diem-vm-validator = { workspace = true }

[features]
failpoints = ["fail/failpoints"]
