[package]
name = "diem-executor-service"
description = "Diem executor service"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
diem-config = { workspace = true }
diem-crypto = { workspace = true }
diem-executor-types = { workspace = true }
diem-language-e2e-tests = { workspace = true }
diem-logger = { workspace = true }
diem-retrier = { workspace = true }
diem-secure-net = { workspace = true }
diem-state-view = { workspace = true }
diem-types = { workspace = true }
diem-vm = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
