name: Check code builds

on:
  push:
    branches:
      - main
      - ci-test
      - add-basic-ci
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  lint-checks:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Print installed Rust toolchains
        run: rustup toolchain list
      - name: Run cargo build
        run:  cargo build

