name: Check code builds

on:
  push:
    branches:
      - main
      - ci-test
      - add-basic-ci
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  lint-checks:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Print installed Rust toolchains
      - name: Install required non-Rust build tools
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          # TODO: check if we need all the packages below -- this list comes from the Libra build setup script
          packages: build-essential lld pkg-config libssl-dev libgmp-dev clang
          version: 1.0 # This is a cache key -- change it when you change the package list above
        run: rustup toolchain list
      - name: Run cargo build
        run:  cargo build

