name: Check code builds

on:
  push:
    branches:
      - release
      - ci-test
  pull_request:
    types: [opened, reopened]
    branches:
      - release

jobs:
  lint-checks:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false
          tool-cache: false
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Print installed Rust toolchains
        run: rustup toolchain list
      - name: Install required non-Rust build tools
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          # TODO: check if we need all the packages below -- this list comes from the Libra build setup script
          packages: build-essential lld pkg-config libssl-dev libgmp-dev clang
          version: 1.0 # This is a cache key -- change it when you change the package list above
      - name: Run cargo build for default packages
        run:  cargo build
      - name: Run cargo build for diem-forge package
        run:  cargo build -p diem-forge
