name: "Release diem-node"
on:
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        required: true
        description: "The release tag to create. E.g. `diem-node-v0.2.3`:"
      branch:
        type: string
        required: true
        description: "The branch to cut the release from"
      release_title:
        type: string
        required: false
        description: 'Name of the release, e.g. "Diem Node Release v1.2.3":'

jobs:
  release-diem-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ inputs.branch }}

      - uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # pin@v4

      - name: Bump diem-node version
        uses: aptos-labs/diem-core/.github/actions/release-diem-node@main
        with:
          release_tag: ${{ inputs.release_tag }}
          diem_node_cargo_toml: diem-node/Cargo.toml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@671dc9c9e0c2d73f07fa45a3eb0220e1622f0c5f # pin@v4
        with:
          add-paths: diem-node
          title: "[diem-node] update release version"
          body: Automated release bump for ${{ inputs.release_tag }}. Change the PR base accordingly
          commit-message: "[diem-node] update release version"
          branch: auto-release-${{ inputs.release_tag }}
          delete-branch: true
